<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>WinMemoryCleaner</RootNamespace>
    <AssemblyName>WinMemoryCleaner</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <NoWarn>$(NoWarn);CS3001;CS3003</NoWarn>
    <ApplicationIcon>Resources\Images\win-memory-cleaner.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <NeutralLanguage>en</NeutralLanguage>
    <ComVisible>false</ComVisible>
    <CLSCompliant>true</CLSCompliant>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DocumentationFile>$(OutputPath)WinMemoryCleaner.xml</DocumentationFile>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DocumentationFile>$(OutputPath)WinMemoryCleaner.xml</DocumentationFile>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <ApplicationDefinition Include="App.xaml" />
    <Page Remove="View\Dialog\MessageDialog.xaml" />
    <Page Remove="View\Window\MainWindow.xaml" />
    <Page Include="View\Window\MainWindow.xaml" />
    <Page Include="View\Dialog\MessageDialog.xaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Localization\*.json" />
    <EmbeddedResource Include="Resources\Themes\*.json" />
    <Resource Include="Resources\Images\win-memory-cleaner.ico" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration.Install" />
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>


</Project>
